### ISSUE TITLE
development: able to change vizzu url

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-ext-js-story#15]
for example use npm install and local version (if jsdelivr blocked by corporate policies)

**Comment by dyuri** [comment]
I'll try to come up with something, constructor is not the best place for this:
- cannot be async (we need to load Vizzu somehow, and we cannot do that in a synchronous way afaik)
- webcomponents are usually instantiated via the DOM parser, and not by calling their constructor

We might check in the `connectedCallback` whether Vizzu is already loaded (in the parent HTML for example), and load it there if it's missing (url can be set via attribute).

**Comment by veghdev** [comment]
@dyuri sorry, i copied the ticket from ipyvizzu-story, of course it does not need to be in the constrsuctor

**Comment by dyuri** [comment]
Please check #16.
Note that the public API has been changed (`vp.vizzu.initialized` => `vp.initialized`)

**Comment by veghdev** [comment]
added in #16
